# Generated by Django 4.2.11 on 2024-04-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='recipe',
            field=models.TextField(default=''),
        ),
    ]
